# To start GPU service use:
#   docker compose --profile gpu up --gpus all
version: "3.8"

services:
  echo-asr-tts:
    build: ./server
    environment:
      ASR_MODEL: small
      ASR_DEVICE: cpu
      ASR_COMPUTE_TYPE: int8
      RU_SPEAKER: kseniya_16khz
      TTS_ENGINE: silero
    ports:
      - "8000:8000"

  echo-asr-tts-gpu:
    profiles: ["gpu"]
    build:
      context: ./server
      dockerfile: Dockerfile.gpu
    environment:
      ASR_MODEL: large-v3
      ASR_DEVICE: cuda
      ASR_COMPUTE_TYPE: float16
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
