# To start GPU service use:
#   docker compose --profile gpu up --gpus all
version: "3.8"

services:
  echo-asr-tts:
    build: ./server
    environment:
      ASR_MODEL: small
      ASR_DEVICE: cpu
      ASR_COMPUTE_TYPE: int8
      RU_SPEAKER: kseniya_16khz
      TTS_ENGINE: silero
    ports:
      - "8000:8000"

  gpu:
    profiles: ["gpu"]
    build:
      context: .
      args:
        BASE_IMAGE: nvidia/cuda:12.1-runtime
    environment:
      ASR_MODEL: ${ASR_MODEL:-small}
      ASR_DEVICE: ${ASR_DEVICE:-cpu}
      ASR_COMPUTE_TYPE: ${ASR_COMPUTE_TYPE:-int8}
      ASR_SR: ${ASR_SR:-16000}
      WS_PORT: ${WS_PORT:-8000}
      HTTP_PORT: ${HTTP_PORT:-8080}
      TTS_ENGINE: ${TTS_ENGINE:-piper}
      RU_SPEAKER: ${RU_SPEAKER:-kseniya_16khz}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
      - "${WS_PORT:-8000}:${WS_PORT:-8000}"
