version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
  redis:
    image: redis:7-alpine
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
  prometheus:
    image: prom/prometheus
  grafana:
    image: grafana/grafana
